// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://actyylqoytcgpcdfgcfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdHl5bHFveXRjZ3BjZGZnY2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTI3MjAsImV4cCI6MjA3MzM2ODcyMH0.G31U89oDcTVy8doV3ubx-9epMhA19xaS9mVhwkWz98g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});